name = "Hugo mADb - modern AsciiDoc blogging theme"
license = "MPL-2.0"
licenselink = "https://github.com/olivecdev/hugo-madb/blob/master/LICENSE"
description = "A humble blogging-focused fork of the great Antora default UI Hugo Theme, with full support for AsciiDoc"
homepage = "https://github.com/olivecdev/hugo-madb"
tags = ["blog", "AsciiDoc", "Asciidoctor", "highlight.js", "rouge.gem", "syntax highlighting"]
features = ["blog", "AsciiDoc", "Asciidoctor", "highlight.js", "rouge.gem", "syntax highlighting"]
min_version = "0.131.0"

[author]
  name = "Carlos Nihelton"
  homepage = "https://cn.olivec.dev"

# If porting an existing theme
[original]
  name = "Antora Default UI Hugo Theme"
  homepage = "https://github.com/basil/antora-default-ui-hugo-theme/"
  repo = "https://github.com/basil/antora-default-ui-hugo-theme/"

